package modelo;
// Generated 22/08/2015 09:16:36 PM by Hibernate Tools 4.3.1

import controlador.Padre;




/**
 * Defectos generated by hbm2java
 */
public class Defectos extends Padre implements java.io.Serializable {


     private Integer idDefecto;
     private Fasesdelproyecto fasesdelproyecto;
     private String codigo;
     private String nombre;

    public Defectos() {
    }

    public Defectos(Fasesdelproyecto fasesdelproyecto, String codigo, String nombre) {
       this.fasesdelproyecto = fasesdelproyecto;
       this.codigo = codigo;
       this.nombre = nombre;
    }
   
    public Integer getIdDefecto() {
        return this.idDefecto;
    }
    
    public void setIdDefecto(Integer idDefecto) {
        this.idDefecto = idDefecto;
    }
    public Fasesdelproyecto getFasesdelproyecto() {
        return this.fasesdelproyecto;
    }
    
    public void setFasesdelproyecto(Fasesdelproyecto fasesdelproyecto) {
        this.fasesdelproyecto = fasesdelproyecto;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


