package modelo;
// Generated 22/08/2015 09:16:36 PM by Hibernate Tools 4.3.1


import controlador.Padre;
import java.util.HashSet;
import java.util.Set;

/**
 * Fases generated by hbm2java
 */
public class Fases extends Padre implements java.io.Serializable {


     private Integer idFase;
     private Usuarios usuarios;
     private String codigo;
     private String nombre;
     private Set fasesdelproyectos = new HashSet(0);

    public Fases() {
    }

	
    public Fases(Usuarios usuarios, String codigo, String nombre) {
        this.usuarios = usuarios;
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Fases(Usuarios usuarios, String codigo, String nombre, Set fasesdelproyectos) {
       this.usuarios = usuarios;
       this.codigo = codigo;
       this.nombre = nombre;
       this.fasesdelproyectos = fasesdelproyectos;
    }
   
    public Integer getIdFase() {
        return this.idFase;
    }
    
    public void setIdFase(Integer idFase) {
        this.idFase = idFase;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getFasesdelproyectos() {
        return this.fasesdelproyectos;
    }
    
    public void setFasesdelproyectos(Set fasesdelproyectos) {
        this.fasesdelproyectos = fasesdelproyectos;
    }
    
     public Fasesdelproyecto getFaseDelProyecto(int idFase){
        
        try {
            
            Object[] fases = this.fasesdelproyectos.toArray();
            
           for(int x=0;x<this.fasesdelproyectos.size();x++){
               Fasesdelproyecto fase =  (Fasesdelproyecto) fases[x];
               
               if(fase.getIdFaseDelProyecto()==idFase){
                   return fase;
               }
               
           }
           
          
             return null;
            
        } catch (Exception e) {
            return null;
        }
        
    }



}


