package modelo;
// Generated 22/08/2015 09:16:36 PM by Hibernate Tools 4.3.1


import controlador.Padre;
import java.util.HashSet;
import java.util.Set;

/**
 * Fasesdelproyecto generated by hbm2java
 */
public class Fasesdelproyecto extends Padre implements java.io.Serializable {


     private Integer idFaseDelProyecto;
     private Fases fases;
     private Proyectos proyectos;
     private Set defectoses = new HashSet(0);

    public Fasesdelproyecto() {
    }

	
    public Fasesdelproyecto(Fases fases, Proyectos proyectos) {
        this.fases = fases;
        this.proyectos = proyectos;
    }
    public Fasesdelproyecto(Fases fases, Proyectos proyectos, Set defectoses) {
       this.fases = fases;
       this.proyectos = proyectos;
       this.defectoses = defectoses;
    }
   
    public Integer getIdFaseDelProyecto() {
        return this.idFaseDelProyecto;
    }
    
    public void setIdFaseDelProyecto(Integer idFaseDelProyecto) {
        this.idFaseDelProyecto = idFaseDelProyecto;
    }
    public Fases getFases() {
        return this.fases;
    }
    
    public void setFases(Fases fases) {
        this.fases = fases;
    }
    public Proyectos getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Proyectos proyectos) {
        this.proyectos = proyectos;
    }
    public Set getDefectoses() {
        return this.defectoses;
    }
    
    public void setDefectoses(Set defectoses) {
        this.defectoses = defectoses;
    }

 public Defectos getDefecto(int idDefecto){
        
        try {
            
            Object[] defectos = this.defectoses.toArray();
            
           for(int x=0;x<this.defectoses.size();x++){
               Defectos defecto =  (Defectos) defectos[x];
               
               if(defecto.getIdDefecto()==idDefecto){
                   return defecto;
               }
               
           }
           
          
             return null;
            
        } catch (Exception e) {
            return null;
        }
        
    }


}


