package modelo;
// Generated 22/08/2015 09:16:36 PM by Hibernate Tools 4.3.1


import controlador.Padre;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * Proyectos generated by hbm2java
 */
public class Proyectos extends Padre implements java.io.Serializable {


     private Integer idProyecto;
     private Usuarios usuarios;
     private String codigo;
     private String nombre;
     private int numeroDeFases;
     private Set fasesdelproyectos = new HashSet(0);

    public Proyectos() {
    }

	
    public Proyectos(Usuarios usuarios, String codigo, String nombre, int numeroDeFases) {
        this.usuarios = usuarios;
        this.codigo = codigo;
        this.nombre = nombre;
        this.numeroDeFases = numeroDeFases;
    }
    public Proyectos(Usuarios usuarios, String codigo, String nombre, int numeroDeFases, Set fasesdelproyectos) {
       this.usuarios = usuarios;
       this.codigo = codigo;
       this.nombre = nombre;
       this.numeroDeFases = numeroDeFases;
       this.fasesdelproyectos = fasesdelproyectos;
    }
   
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getNumeroDeFases() {
        return this.numeroDeFases;
    }
    
    public void setNumeroDeFases(int numeroDeFases) {
        this.numeroDeFases = numeroDeFases;
    }
    public Set getFasesdelproyectos() {
        return this.fasesdelproyectos;
    }
    
    public void setFasesdelproyectos(Set fasesdelproyectos) {
        this.fasesdelproyectos = fasesdelproyectos;
    }
    
    public void addFaseDelProyecto(Fasesdelproyecto  fasesdelproyecto){
        this.fasesdelproyectos.add(fasesdelproyecto);
    }
    
     public Fasesdelproyecto getFaseDelProyecto(int idFaseDelProyecto){
        
        try {
            
            Object[] fases = this.fasesdelproyectos.toArray();
            
           for(int x=0;x<this.fasesdelproyectos.size();x++){
               Fasesdelproyecto fase =  (Fasesdelproyecto) fases[x];
               
               if(fase.getIdFaseDelProyecto()==idFaseDelProyecto){
                   return fase;
               }
               
           }
           
          
             return null;
            
        } catch (Exception e) {
            return null;
        }
        
    }
         
    public Vector<Fases> getVectorFasesDelProyecto(){
        try {
                 
           Object[] fases = this.fasesdelproyectos.toArray();
           Vector<Fases> vector = new Vector();
           
           for(int x =0; x<this.fasesdelproyectos.size();x++){
               Fases fase = (Fases) fases[x];
              vector.add(fase);
           }
           
           return vector;
           
            
        } catch (Exception e) {
           
            return null;
        }
    }

    @Override
    public String toString() {
        return this.nombre;
    }


}


